# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use
# For example: application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/reference/features/profiles.html
# ===================================================================

logging:
  level:
    root: debug
    com.dct.nextgen: debug
    org.springframework.security: debug
  charset:
    console: UTF-8
    file: UTF-8
  # Custom properties to define logs file paths according to different profiles
  file-path: mnt/logs

spring:
  jpa:
    # Avoid causing LazyInitializationException if querying outside the scope of EntityManager or causing poor performance
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        jdbc:
          time_zone: UTC
          ddl-auto: validate
    hibernate:
      # Hibernate only checks if the current schema matches the entity
      # If it does not match, the application will not start
      # Do not make any changes to the schema
      ddl-auto: validate
  thymeleaf:
    cache: false
  sql:
    init:
      mode: never

server:
  servlet:
    session:
      cookie:
        # The session cookie that Spring Boot creates will have the HttpOnly attribute
        # Setting HttpOnly helps protect cookies from Cross-Site Scripting (XSS) attacks
        # Cookies will still be sent with each HTTP request (and can therefore be used for session authentication)
        # But Cookies cannot be accessed from the client side using JavaScript (e.g. via document.cookie)
        http-only: true
  port: 8000

dct-base:
  domain: http://localhost:${server.port}

  jpa:
    persistence-unit-name: dct-nextgen-persistence
    base-entity-packages:
      - com.dct.nextgen.entity
    base-repository-packages:
      - com.dct.nextgen.repositories

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: jdbc:mysql://localhost:3306/nextgen_brand?serverTimezone=UTC
    username: admin-nextgen-brand
    password: 123456a@
    hikari:
      poolName: Hikari
      # AllowPoolSuspension means pause connection when there is a problem
      # When the setting is false, the system will not allow to pause connections in pool
      # Helping to maintain continuous system operation even when there is a problem
      allow-pool-suspension: false
      auto-commit: false # Do not automatically commit transactions
      maximumPoolSize: 20 # Maximum database connections
      minimumIdle: 4 # At least connections will be kept idle, ready for use
      maxLifetime: 1200000 # Maximum time (20 minutes) that a connection can exist in the pool before being closed and recreated
      idleTimeout: 600000 # Maximum time (10 minutes) that a connection can be idle before being closed
      connectionTimeout: 60000 # Maximum time (1 minutes) to wait for connection from pool when no connection is available
      leak-detection-threshold: 60000 # If a connection is not returned to the pool after 2 minutes, it will be detected as a "leak"
      datasource-properties:
        cachePrepStmts: true # Enable caching to improve performance when using multiple identical statements
        prepStmtCacheSize: 100 # Prepared statement cache size. In this case, the cache can hold up to 100 statements
        prepStmtCacheSqlLimit: 1024 # Limits the maximum length (in bytes) of an SQL statement that can be cached
        useServerPrepStmts: true # Enable server-side prepared statements instead of client-side prepared statements

  security:
    auth:
      enabled-tls: false
      base64-secret-key: ZGN0LWJhc2Utc2VjcmV0LWtleS10b2tlbi12YWxpZGl0eS04NjQwMDAwMG1zLWZvci1yZW1lbWJlci1tZS04NjQwMDAwMG1z
      # Token is valid default in 1 hour and 24 hours for remember me
      token-validity: 3600000 # milliseconds
      token-validity-for-remember-me: 86400000 # milliseconds

  resources:
    upload:
      upload-path: D:/Downloads/nextgen/
